### ISSUE TITLE
1.17.1 & 1.18 compatibility / island creation issue

### ISSUE THREAD

**Issue by ElBananaa** [aglerr/SSB2-AdvancedSlimeWorldManager#2]
Hey!
I was looking for a fork of the original addon and Ome_R sent me a link to yours. Thanks for making a public fork of the plugin!

I installed it, but for an unknown reason, when I try to create an island, the creation task is endless.
There's no errors, but I can't go to the island, I don't know why. 

My server is running Purpur 1.17.1 #1428 under Java 17.0.1 & SSB2 1.8.3 b382 (With MySQL enabled & working)
I am using the latest version of the ASWM-classmodifier & ASWM-Plugin (2.7.0 build 502), as same as the latest version of your plugin, and both ASWM & your plugin are configured to save data in files (I also tried mysql, it didn't help).

I did follow the setup instructions given on https://github.com/Paul19988/Advanced-Slime-World-Manager/blob/develop/.docs/usage/install.md

I also created a world named SuperiorWorld (as this was necessary with ASWM fork of this plugin), it still didn't solve the issue.
I also noticed the island file is created when I create an island, however, it isn't stored in the world.yml file, and same when using mysql to save the data.

Could you please do anything about that?

**Comment by mdaffa48** [comment]
@ElBananaa by endless, do you mean the island creation process never be completed?

I haven't really check this addon code in a long time, I'll spare my time to update the code so anybody can use it without issues or anything. I'll you keep updated here.

**Comment by mdaffa48** [comment]
@ElBananaa I have released a new version today, I haven't really tested properly, let me know the results!
https://github.com/aglerr/SSB2-AdvancedSlimeWorldManager/releases/tag/1.0.4

Also the answer for your question about:
> I also noticed the island file is created when I create an island, however, it isn't stored in the world.yml file, and same when using mysql to save the data.

Yes the SWM will create a file for the world, but the world will not be saved on the `worlds.yml`, the file will be on the `slime_worlds` directory (by default) and SSB2 will load the world directly from that directory. And last time I tested using mysql, it will save the world on the mysql.

**Comment by ElBananaa** [comment]
@aglerr Hey,
Thanks, I really appreciate it!

Yes, by endless I meant the creation process is stuck. I tried with the latest version, but I'm still experiencing the same issue.
Basically, when I create an island, it simply says `Processing your request`.
I can open the island panel, however when I try to go on the island, it says : `It seems like this island has no safe blocks. Please contact a staff member`. 
I can disband the island, but then, when I try to create a new one, it says : `You have an already ongoing island creation task.`

**Comment by mdaffa48** [comment]
> @aglerr Hey, Thanks, I really appreciate it!
> 
> Yes, by endless I meant the creation process is stuck. I tried with the latest version, but I'm still experiencing the same issue. Basically, when I create an island, it simply says `Processing your request`. I can open the island panel, however when I try to go on the island, it says : `It seems like this island has no safe blocks. Please contact a staff member`. I can disband the island, but then, when I try to create a new one, it says : `You have an already ongoing island creation task.`

When you try to create island, does anything show up on the console? Like maybe a log to create the world or something. I just tested it 3 hours ago, The island creation process always completed, never fails.

**Comment by ElBananaa** [comment]
> > @aglerr Hey, Thanks, I really appreciate it!
> > Yes, by endless I meant the creation process is stuck. I tried with the latest version, but I'm still experiencing the same issue. Basically, when I create an island, it simply says `Processing your request`. I can open the island panel, however when I try to go on the island, it says : `It seems like this island has no safe blocks. Please contact a staff member`. I can disband the island, but then, when I try to create a new one, it says : `You have an already ongoing island creation task.`
> 
> When you try to create island, does anything show up on the console? Like maybe a log to create the world or something. I just tested it 3 hours ago, The island creation process always completed, never fails.

Here's the full console log when creating an island: https://pastebin.com/9yewJdi9.
Am I missing a setup step or anything like that? I truly have no idea why it's not working properly for me ^^

**Comment by ElBananaa** [comment]
Alright, so I just tried to reproduce the issue on a local test server (fresh install), with purpur 1.17.1 #1428, ssb2 1.8.2 b387, and aswm, and I still have the same issue, and no errors, and the i'm using file saving for the data, in both ASWM & SSB2.
Same result: Can create an island but the creation process is endless, can't go to the island but I can disband it, and I can't create another island since the creation process nevers ends.

Here's the full server log: https://gist.github.com/ElBananaa/8a9f4d87669fcf01e7d834818349361b

**Comment by mdaffa48** [comment]
@ElBananaa I tested on 1.17.1 and got the same problem as yours. Currently I don't know how to fix that at all, the world creation suddenly just stopped after creating the world with `NORMAL` environment, and the rest (`NETHER`, `THE_END`) never created.

**Comment by ElBananaa** [comment]
@aglerr I wish I could help, but I really don't know how world generation works in 1.17/1.18. I'd be more than happy to help with debugging if you need tho! I believe I've seen a lot of things related to world generation on ASWM discord server, so you should probably try to take a look at it.
Anyways, thanks for trying to reproduce the issue! :)

**Comment by EnZiiK** [comment]
There you have an answer 
![4FAD05C5-52B3-4A5D-8B5D-761B63322D74](https://user-images.githubusercontent.com/59665116/145222107-e3e63e25-9fcc-447e-a2e5-5c9f180f4c38.jpeg)

I wasted month of my life to make it work but this is problem of SSB2

**Comment by OmerBenGera** [comment]
Sounds like something is blocking SSB from placing blocks in the custom worlds.
Find what it is, and I will be more than happy to fix it if it turns to be something I need to change.
I don't think it has something to do with the plugin tho, as it works fine on normal worlds.

**Comment by ElBananaa** [comment]
Hey,
As @aglerr said, the plugin was working properly during his first tests, however, it doesn't with 1.17+, so this must be something related to the server version, and not to SSB2, right?

As I said, I'd like to help, but I don't have the knowledge to do so unfortunately, but if you guys want to test anything, just let me know ^^

**Comment by EnZiiK** [comment]
Yes, it was working on ASWM version 2.6.2 and SSB2 dev version 180+-.
But there was lot of changes in ASWM and SSB2 from these versions till now. And its really hard to find what cause it.

**Comment by DuneSciFye** [comment]
I also have this issue, will this be fixed?

**Comment by OmerBenGera** [comment]
After some investigation, the issue turned to be incompatibility with ASWM itself.
ASWM creates worlds without a generator, caused the plugin to throw an error. This error was not detected correctly by the plugin, causing the creation process of islands to never success or fail - or in other words, to hang.
Both issues were addressed - first, the plugin will now detect every error and handle it correctly; secondly, the plugin respects null chunk generators and will still let worlds to generate.

However, when teleporting to your islands after a restart, there seems to be errors with Paper's anti-xray. If you get errors and your server crash, just disable the anti-xray of Paper (which is pointless anyways on a skyblock server)

@ElBananaa @EnZiiK @DuneSciFye Update to latest dev build of SSB to get the plugin working.

@aglerr , I believe this issue can be closed :)

**Comment by ElBananaa** [comment]
Awesome!
Thanks for taking a look at this, I'll give it a shot asap and keep you both updated on this.
